export const destinations = [
  {
    city: 'Osh',
    country: 'Kyrgyzstan',
    flag: '🇰🇬',
    from: '$320',
    hero: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1400&q=85',
    description: {
      en: "Osh is one of Central Asia's oldest cities, nestled in the fertile Fergana Valley at the foot of the Tian Shan mountains. Known as the \"southern capital\" of Kyrgyzstan, Osh served as a key stop on the ancient Silk Road and preserves thousands of years of history within its labyrinthine bazaars and sacred mountain.",
      ru: 'Ош — один из древнейших городов Центральной Азии, расположенный в плодородной Ферганской долине у подножия гор Тянь-Шань. Известный как «южная столица» Кыргызстана, Ош был важной остановкой на древнем Шёлковом пути.',
      uz: "Osh - Markaziy Osiyoning eng qadimiy shaharlaridan biri, Farg'ona vodiysida Tyanshan tog'lari etagida joylashgan. Qirgizistonning «janubiy poytaxti» sifatida tanilgan Osh qadimiy Ipak yo'lining muhim bekatlaridan biri bo'lgan.",
    },
    highlights: [
      { icon: '🏔️', title: 'Sulaiman-Too',    desc: { en: 'UNESCO World Heritage sacred mountain rising above the city', ru: 'Священная гора под охраной ЮНЕСКО', uz: "YuNESKO Jahon merosi ob'ekti - muqaddas tog'" } },
      { icon: '🏪', title: 'Osh Bazaar',       desc: { en: "One of Central Asia's largest and oldest traditional markets", ru: 'Один из крупнейших традиционных базаров Центральной Азии', uz: "Markaziy Osiyoning eng katta va qadimiy bozorlaridan biri" } },
      { icon: '🕌', title: 'Silk Road Legacy', desc: { en: '3,000 years of history along the ancient trade route', ru: '3000 лет истории вдоль древнего торгового пути', uz: "Qadimiy savdo yo'li bo'ylab 3000 yillik tarix" } },
      { icon: '🏕️', title: 'Yurt Stays',       desc: { en: 'Authentic nomadic stays in the surrounding Kyrgyz steppe', ru: 'Аутентичный ночлег в юрте в кыргызской степи', uz: "Qirgiz dashtlarida haqiqiy ko'chmanchi yurt qoshida qolish" } },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=700&q=80',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=700&q=80',
      'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=700&q=80',
    ],
    stats: { bestTime: 'Apr – Oct', language: 'Kyrgyz / Russian', currency: 'KGS', population: '310K' },
  },
  {
    city: 'Tashkent',
    country: 'Uzbekistan',
    flag: '🇺🇿',
    from: '$290',
    hero: 'https://images.unsplash.com/photo-1573108724029-4c46571d6490?auto=format&fit=crop&w=1400&q=85',
    description: {
      en: "Tashkent is the vibrant capital of Uzbekistan — a city where Soviet-era grand boulevards meet ancient Islamic architecture and ultra-modern skylines. As the largest city in Central Asia, it is the gateway to the legendary Silk Road cities of Samarkand and Bukhara.",
      ru: 'Ташкент — яркая столица Узбекистана, где советские проспекты встречаются с древней исламской архитектурой и ультрасовременными небоскрёбами. Крупнейший город Центральной Азии.',
      uz: "Toshkent - O'zbekistonning yashnoq poytaxti, sovet davri shoh ko'chalari qadimiy islom me'morchiligi bilan uyg'unlashgan shahar. Markaziy Osiyoning eng yirik shahri.",
    },
    highlights: [
      { icon: '🏛️', title: 'Khast Imam',        desc: { en: 'Historic Islamic complex with 7th-century Quran manuscript', ru: 'Исторический исламский комплекс с рукописью Корана VII века', uz: '7-asr Qur\'on qo\'lyozmasi saqlanadigan tarixiy majmua' } },
      { icon: '🚇', title: 'Metro Art',          desc: { en: 'Soviet-era metro stations decorated like marble palaces', ru: 'Станции метро советской эпохи, украшенные как мраморные дворцы', uz: "Marmar saroylari kabi bezatilgan sovet metro stansiyalari" } },
      { icon: '🍴', title: 'Plov Culture',       desc: { en: 'World-famous Uzbek plov cooked fresh at Osh Bazaar daily', ru: 'Всемирно известный узбекский плов, ежедневно готовящийся на Ош базаре', uz: "Har kuni yangi pishiriladigan dunyo mashhur o'zbek oshi" } },
      { icon: '🌳', title: 'Chorsu Bazaar',      desc: { en: 'Iconic domed bazaar at the heart of the old city', ru: 'Знаменитый базар с куполом в центре старого города', uz: "Eski shahar markazidagi mashhur gumbazli bozor" } },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=700&q=80',
      'https://images.unsplash.com/photo-1549944850-84e00be4203b?auto=format&fit=crop&w=700&q=80',
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=700&q=80',
    ],
    stats: { bestTime: 'Mar – May, Sep – Nov', language: 'Uzbek', currency: 'UZS', population: '3.2M' },
  },
  {
    city: 'Tokyo',
    country: 'Japan',
    flag: '🇯🇵',
    from: '$680',
    hero: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1400&q=85',
    description: {
      en: 'Tokyo is a dazzling mega-city where ancient temples share the skyline with futuristic towers. From the bustling streets of Shibuya to the serene gardens of Shinjuku, Tokyo offers an unrivaled blend of tradition and innovation, world-class cuisine, and pop culture.',
      ru: 'Токио — ослепительный мегаполис, где древние храмы соседствуют с футуристическими башнями. От оживлённых улиц Сибуи до безмятежных садов Синдзюку.',
      uz: "Tokio - qadimiy ibodatxonalar futuristik minoralar bilan uyg'unlashgan ajoyib megapolis. Shibuya ko'chalaridan Shinjuku bog'larigacha.",
    },
    highlights: [
      { icon: '⛩️', title: 'Senso-ji Temple',  desc: { en: "Tokyo's oldest Buddhist temple in the heart of Asakusa", ru: 'Старейший буддийский храм Токио в центре Асакусы', uz: "Asakusa markazidagi Tokioning eng qadimiy buddist ibodatxonasi" } },
      { icon: '🗼', title: 'Tokyo Tower',       desc: { en: 'Iconic 333m tower with panoramic views of the city', ru: 'Культовая башня высотой 333 м с панорамным видом', uz: "Shaharning panoramik ko'rinishiga ega 333 metrlik minora" } },
      { icon: '🍜', title: 'Ramen & Sushi',    desc: { en: 'World-class culinary scene with Michelin-starred restaurants', ru: 'Кулинарная сцена мирового класса с ресторанами со звёздами Мишлен', uz: "Mishlen yulduzli restoranlar bilan jahon darajasidagi oshxona" } },
      { icon: '🌸', title: 'Sakura Season',    desc: { en: 'Spectacular cherry blossom viewing in Ueno Park each spring', ru: 'Великолепное цветение сакуры в парке Уэно каждую весну', uz: "Har bahar Ueno bog'ida ajoyib sakura gullash mavsumi" } },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1513407030348-c983a97b98d8?auto=format&fit=crop&w=700&q=80',
      'https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=700&q=80',
      'https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?auto=format&fit=crop&w=700&q=80',
    ],
    stats: { bestTime: 'Mar – May, Oct – Nov', language: 'Japanese', currency: 'JPY', population: '13.9M' },
  },
  {
    city: 'Paris',
    country: 'France',
    flag: '🇫🇷',
    from: '$420',
    hero: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=1400&q=85',
    description: {
      en: 'Paris, the City of Light, captivates every visitor with its timeless elegance — from the iron lace of the Eiffel Tower to the grandeur of the Louvre. World-renowned for its cuisine, fashion, art, and café culture, Paris is a destination that never loses its magic.',
      ru: 'Париж, Город Света, восхищает каждого посетителя своей вечной элегантностью — от кружевного железа Эйфелевой башни до величия Лувра.',
      uz: "Parij - Nur shahri, Eyfel minorasining metall to'ri va Luvrning ulug'vorligidan tortib har bir mehmonni o'ziga asir etuvchi shahar.",
    },
    highlights: [
      { icon: '🗼', title: 'Eiffel Tower',     desc: { en: 'The world\'s most iconic landmark, best at sunset', ru: 'Самая известная достопримечательность мира, особенно красивая на закате', uz: "Quyosh botishida eng yaxshi ko'rinadigan dunyoning eng mashhur yodgorligi" } },
      { icon: '🖼️', title: 'The Louvre',        desc: { en: "World's largest art museum with 35,000 artworks", ru: 'Крупнейший художественный музей мира с 35 000 произведениями искусства', uz: "35 000 san'at asarlariga ega dunyoning eng yirik san'at muzeyi" } },
      { icon: '🥐', title: 'Café Culture',      desc: { en: 'Legendary Parisian bistros and patisseries on every corner', ru: 'Легендарные парижские бистро и кондитерские на каждом углу', uz: "Har burchakda afsonaviy parij bistrolar va pechivolar" } },
      { icon: '🛍️', title: 'Haute Couture',    desc: { en: 'Fashion capital of the world on the Champs-Élysées', ru: 'Мировая столица моды на Елисейских полях', uz: "Champs-Élysées ko'chasida dunyo moda poytaxti" } },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=700&q=80',
      'https://images.unsplash.com/photo-1541410702738-f87a5449e456?auto=format&fit=crop&w=700&q=80',
      'https://images.unsplash.com/photo-1520939817895-060bdaf4fe1b?auto=format&fit=crop&w=700&q=80',
    ],
    stats: { bestTime: 'Apr – Jun, Sep – Oct', language: 'French', currency: 'EUR', population: '2.2M' },
  },
  {
    city: 'Berlin',
    country: 'Germany',
    flag: '🇩🇪',
    from: '$560',
    hero: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=1400&q=85',
    description: {
      en: 'Berlin is a cultural powerhouse where history meets cutting-edge design. From the Brandenburg Gate to Museum Island, the city offers world-class museums, memorable street food, and a vibrant arts scene.',
      ru: 'Берлин — культурный центр, где история встречается с современным дизайном. От Бранденбургских ворот до Острова музеев — город предлагает музеи мирового класса, уличную еду и живую арт-сцену.',
      uz: 'Berlin - tarix zamonaviy dizayn bilan uchrashadigan madaniyat markazi. Brandenburg darvozalaridan Muzey oroligacha shahar dunyo darajasidagi muzeylar, ko‘cha taomi va jonli sanʼat muhitini taqdim etadi.',
    },
    highlights: [
      { icon: '🏛️', title: 'Brandenburg Gate', desc: { en: 'Iconic neoclassical monument at the heart of Berlin', ru: 'Знаменитый неоклассический памятник в центре Берлина', uz: 'Berlin markazidagi mashhur neoklassik haykal' } },
      { icon: '🖼️', title: 'Museum Island',   desc: { en: 'Five world-renowned museums on a historic island in the Spree', ru: 'Пять всемирно известных музеев на историческом острове Шпрее', uz: 'Shpreke tarixiy orolida joylashgan beshta jahon shonli muzey' } },
      { icon: '🎨', title: 'Street Art',      desc: { en: 'Vibrant murals and murals along the East Side Gallery', ru: 'Яркие фрески на Восточной стороне Галереи', uz: 'East Side Gallery bo‘ylab rang-barang street-art' } },
      { icon: '🍻', title: 'Local Beer',      desc: { en: 'Traditional beer gardens and modern craft breweries across the city', ru: 'Традиционные пивные сады и современные крафтовые пивоварни по всему городу', uz: 'Shahar bo‘ylab anʼanaviy pivo bog‘lari va zamonaviy craft pivo zavodlari' } },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1468067333380-13c4cba5e1da?auto=format&fit=crop&w=700&q=80',
      'https://images.unsplash.com/photo-1508051123996-69f8caf4891b?auto=format&fit=crop&w=700&q=80',
      'https://images.unsplash.com/photo-1526512340740-9215f6a0e18f?auto=format&fit=crop&w=700&q=80',
    ],
    stats: { bestTime: 'Apr – Oct', language: 'German', currency: 'EUR', population: '3.7M' },
  },
  {
    city: 'Dubai',
    country: 'UAE',
    flag: '🇦🇪',
    from: '$590',
    hero: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1400&q=85',
    description: {
      en: 'Dubai is a city of superlatives — the tallest building, the largest mall, the only 7-star hotel. This Emirati gem on the Arabian Gulf has transformed from a small fishing village to a global icon of luxury, architecture, and ambition in just a few decades.',
      ru: 'Дубай — город превосходных степеней: самое высокое здание, крупнейший торговый центр. Этот эмиратский бриллиант на Аравийском заливе за несколько десятилетий превратился в мировой символ роскоши.',
      uz: "Dubay - eng uzun bino, eng katta savdo markazi va yagona 7 yulduzli mehmonxonaga ega superlativlar shahri. Bir necha o'n yil ichida baliqchilik qishlog'idan jahon hashamat ramziga aylandi.",
    },
    highlights: [
      { icon: '🏙️', title: 'Burj Khalifa',    desc: { en: "World's tallest tower at 828m with sky-high observation deck", ru: 'Самая высокая башня в мире высотой 828 м со смотровой площадкой', uz: "828 metr balandlikdagi dunyoning eng baland minorasi" } },
      { icon: '🏖️', title: 'Jumeirah Beach',   desc: { en: 'Pristine white sand beach with views of Burj Al Arab', ru: 'Первозданный белый пляж с видом на Бурдж-эль-Араб', uz: "Burj Al Arab ko'rinishi bilan zangsiz oq qumli plyaj" } },
      { icon: '🛶', title: 'Dubai Creek',       desc: { en: 'Historic waterway with traditional wooden abra boats', ru: 'Историческая водная артерия с традиционными деревянными лодками', uz: "An'anaviy yog'och abra qayiqlari bilan tarixiy suv yo'li" } },
      { icon: '🌅', title: 'Desert Safari',     desc: { en: 'Sunset dune bashing followed by a Bedouin camp dinner', ru: 'Езда по дюнам на закате и ужин в лагере бедуинов', uz: "Quyosh botishi paytida qumtepalarda sürme va Badaviy lagerida kechki ovqat" } },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=700&q=80',
      'https://images.unsplash.com/photo-1526495124232-a04e1849168c?auto=format&fit=crop&w=700&q=80',
      'https://images.unsplash.com/photo-1467244312836-9a6f4e670a7f?auto=format&fit=crop&w=700&q=80',
    ],
    stats: { bestTime: 'Nov – Mar', language: 'Arabic / English', currency: 'AED', population: '3.5M' },
  },
  {
    city: 'Bali',
    country: 'Indonesia',
    flag: '🇮🇩',
    from: '$540',
    hero: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1400&q=85',
    description: {
      en: "Bali, the Island of the Gods, enchants travelers with its dramatic volcanic landscape, lush rice terraces, spiritual Hindu temples, and world-class surf breaks. Whether you seek yoga retreats, vibrant nightlife, or serene rice-field walks, Bali delivers it all.",
      ru: "Бали, Остров богов, очаровывает путешественников своим живописным вулканическим ландшафтом, пышными рисовыми террасами и духовными индуистскими храмами.",
      uz: "Xudolar oroli Bali sayohatchilarni o'zining vulqonli landshafti, sersuv sholi maydonlari, ruhiy hindu ibodatxonalari va jahon darajasidagi to'lqin surfinglar bilan o'ziga jalb etadi.",
    },
    highlights: [
      { icon: '🛕', title: 'Tanah Lot',         desc: { en: 'Iconic sea temple perched on a rocky offshore island', ru: 'Культовый морской храм на скалистом острове в море', uz: "Qoyali dengiz orolida joylashgan mashhur dengiz ibodatxonasi" } },
      { icon: '🌾', title: 'Tegallalang Rice',  desc: { en: 'Spectacular UNESCO rice terraces in the highlands of Ubud', ru: 'Великолепные рисовые террасы ЮНЕСКО в горах Убуда', uz: "Ubud tog'larida ajoyib YuNESKO sholi terrasalari" } },
      { icon: '🏄', title: 'Surf & Waves',      desc: { en: "World-class surf at Uluwatu, Canggu and Seminyak beaches", ru: 'Серфинг мирового класса на пляжах Улувату, Чангу и Семиньяк', uz: "Uluwatu, Canggu va Seminyak plyajlarida jahon darajasidagi surfing" } },
      { icon: '💆', title: 'Spa & Wellness',    desc: { en: 'Traditional Balinese massage and luxury jungle retreats', ru: 'Традиционный балийский массаж и роскошные ретриты в джунглях', uz: "An'anaviy Bali massaji va hashamatli o'rmon retretlari" } },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1555400038-63f5ba517a47?auto=format&fit=crop&w=700&q=80',
      'https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?auto=format&fit=crop&w=700&q=80',
      'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=700&q=80',
    ],
    stats: { bestTime: 'Apr – Oct', language: 'Balinese / Indonesian', currency: 'IDR', population: '4.2M' },
  },
  {
    city: 'New York',
    country: 'USA',
    flag: '🇺🇸',
    from: '$380',
    hero: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=1400&q=85',
    description: {
      en: "New York City, the city that never sleeps, is the world's ultimate urban destination. From the neon-lit chaos of Times Square to the tranquil green of Central Park, from Broadway theatre to Brooklyn street food — NYC is an endless sensory adventure.",
      ru: "Нью-Йорк, город, который никогда не спит, — главное городское направление в мире. От хаоса Таймс-сквер с неоновой подсветкой до тихой зелени Центрального парка.",
      uz: "Nyu-York - hech qachon uxlamaydigan shahar, dunyoning eng yaxshi shahar destinatsiyasi. Times Squarening neon chyrog'laridan Central Parkgacha.",
    },
    highlights: [
      { icon: '🗽', title: 'Statue of Liberty', desc: { en: 'Iconic symbol of freedom on Liberty Island in the harbour', ru: 'Культовый символ свободы на острове Либерти в гавани', uz: "Harbour orolida erkinlik ramzi - Ozodlik haykali" } },
      { icon: '🌳', title: 'Central Park',      desc: { en: '341 hectares of urban green in the heart of Manhattan', ru: '341 гектар городской зелени в самом сердце Манхэттена', uz: "Manhetten markazida 341 gektar shahardagi yashillik" } },
      { icon: '🎭', title: 'Broadway',           desc: { en: 'World-famous theatre district with nightly world-class shows', ru: 'Всемирно известный театральный квартал с ежевечерними постановками', uz: "Har kecha jahon darajasidagi spektakllar bilan mashhur teatr tumani" } },
      { icon: '🍕', title: 'NYC Food Scene',    desc: { en: "From dollar pizza slices to Michelin-starred fine dining", ru: 'От пиццы за доллар до ресторанов со звёздами Мишлен', uz: "Dollar pizzadan Mishlen yulduzli restoranlargacha" } },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1546436836-07a91091f160?auto=format&fit=crop&w=700&q=80',
      'https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?auto=format&fit=crop&w=700&q=80',
      'https://images.unsplash.com/photo-1522083165195-3424ed129620?auto=format&fit=crop&w=700&q=80',
    ],
    stats: { bestTime: 'Apr – Jun, Sep – Nov', language: 'English', currency: 'USD', population: '8.3M' },
  },
  {
    city: 'Santorini',
    country: 'Greece',
    flag: '🇬🇷',
    from: '$710',
    hero: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1400&q=85',
    description: {
      en: "Santorini is the jewel of the Aegean — a volcanic island of breathtaking sunsets, whitewashed clifftop villages, and deep-blue caldera views. Famous for its iconic blue-domed churches in Oia, volcanic black sand beaches, and world-class Greek wine.",
      ru: 'Санторини — жемчужина Эгейского моря: вулканический остров с захватывающими закатами, белоснежными деревнями на скалах и видами на синюю кальдеру.',
      uz: "Santorini - Egey dengizining dur-i begi: nafas oladigan quyosh botishlari, qor-oq qoya qishloqlari va chuqur ko'k kaldera ko'rinishlari bilan vulqonli orol.",
    },
    highlights: [
      { icon: '🌅', title: 'Oia Sunset',         desc: { en: "World's most photographed sunset from the clifftop village", ru: 'Самый фотографируемый в мире закат из деревни на скале', uz: "Qoya ustidagi qishloqdan dunyoning eng ko'p fotografiyaga olinadigan quyosh botishi" } },
      { icon: '🏛️', title: 'Ancient Akrotiri',   desc: { en: "Minoan Bronze Age city preserved under volcanic ash", ru: 'Минойский город бронзового века, сохранившийся под вулканическим пеплом', uz: "Vulqon kuli ostida saqlanib qolgan bronza davri Minoy shahri" } },
      { icon: '🍷', title: 'Volcanic Wines',     desc: { en: 'Unique Assyrtiko white wine from volcanic soil vineyards', ru: 'Уникальное белое вино Assyrtiko с виноградников на вулканической почве', uz: "Vulqon tuproqli uzumzorlardan noyob Assyrtiko oq sharob" } },
      { icon: '⛵', title: 'Caldera Cruise',     desc: { en: 'Sail around the volcanic caldera and hot springs at sunset', ru: 'Плавание вокруг вулканической кальдеры и горячих источников на закате', uz: "Quyosh botishida vulqon kalderi va issiq buloqlar atrofida suzish" } },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?auto=format&fit=crop&w=700&q=80',
      'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?auto=format&fit=crop&w=700&q=80',
      'https://images.unsplash.com/photo-1602088113235-229c19758e9f?auto=format&fit=crop&w=700&q=80',
    ],
    stats: { bestTime: 'Apr – Oct', language: 'Greek', currency: 'EUR', population: '15K' },
  },
];
